### ISSUE TITLE
gfortran compile error for github oce

### ISSUE THREAD

**Issue by paleolimbot** [ArgoCanada/argoFloats#357]
I see there's a [failure installing oce in GitHub actions](https://github.com/ArgoCanada/argoFloats/runs/1708311159#step:4:430). I've run across this working on sf before as well...you can add this to the actions to fix (I think!):

``` yaml
- name:  Ensure gfortran exists on macOS
        if: runner.os == 'macOS'
        run: |
          # conflicts with gfortran from r-lib/actions when linking gcc
          rm '/usr/local/bin/gfortran'
```
